# Generated by Django 4.0.5 on 2022-06-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speed_test_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.CharField(blank=True, max_length=30)),
                ('upload_speed', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
